#!/bin/bash
set -e

TABLES="${TABLES:-10}"
THREADS="${THREADS:-10}"
TABLE_SIZE="${TABLE_SIZE:-100}"
GYMONGODB_DB="${GYMONGODB_DB:-gymongonasium}"
GYMONGODB_HOST="${GYMONGODB_HOST:-mongodb}"
GYMONGODB_PORT="${GYMONGODB_PORT:-27017}"
TIME="${TIME:-120}"
SLEEP="${SLEEP:-5}"

runbench () {
  echo 'running bench'
  echo prepare
  cd /usr/local/sysbench-mongodb-lua
	sysbench oltp-mongo.lua --tables=$TABLES --threads=$THREADS --table-size=$TABLE_SIZE --mongodb-db=$GYMONGODB_DB --mongodb-host=$GYMONGODB_HOST --mongodb-port=$GYMONGODB_PORT prepare
  echo run
	sysbench oltp-mongo.lua --tables=$TABLES --threads=$THREADS --table-size=$TABLE_SIZE --mongodb-db=$GYMONGODB_DB --mongodb-host=$GYMONGODB_HOST --mongodb-port=$GYMONGODB_PORT --time=$TIME run
  echo cleanup
	sysbench oltp-mongo.lua --tables=$TABLES --threads=$THREADS --table-size=$TABLE_SIZE --mongodb-db=$GYMONGODB_DB --mongodb-host=$GYMONGODB_HOST --mongodb-port=$GYMONGODB_PORT cleanup
}

echobench () {
  cd /usr/local/sysbench-mongodb-lua
  pwd
  ls
	echo "sysbench oltp-mongo.lua --tables=$TABLES --threads=$THREADS --table-size=$TABLE_SIZE --mongodb-db=$GYMONGODB_DB --mongodb-host=$GYMONGODB_HOST --mongodb-port=$GYMONGODB_PORT prepare"
	echo "sysbench oltp-mongo.lua --tables=$TABLES --threads=$THREADS --table-size=$TABLE_SIZE --mongodb-db=$GYMONGODB_DB --mongodb-host=$GYMONGODB_HOST --mongodb-port=$GYMONGODB_PORT --time=$TIME run"
	echo "sysbench oltp-mongo.lua --tables=$TABLES --threads=$THREADS --table-size=$TABLE_SIZE --mongodb-db=$GYMONGODB_DB --mongodb-host=$GYMONGODB_HOST --mongodb-port=$GYMONGODB_PORT cleanup"
}

echoperf () {
  which python
  cd /usr/local/mongo-perf
  python -V
  pwd
  ls
  echo \
  python benchrun.py \
    -f testcases/* \
    -t 1 2 4 \
    --includeFilter insert update \
    --includeFilter core \
	  --host $GYMONGODB_HOST \
    --port $GYMONGODB_PORT \
    --threads $THREADS \
    --multidb $TABLES \
    --trialTime $TIME
}

runperf () {
  echo 'running mongo-perf'
  cd /usr/local/mongo-perf
  pwd
  ls
  python benchrun.py \
    -f testcases/simple_insert.js \
	  --host $GYMONGODB_HOST \
    --port $GYMONGODB_PORT \
    --threads $THREADS
}

runperf-full () {
  echo 'running mongo-perf'
  cd /usr/local/mongo-perf
  pwd
  ls
  python benchrun.py \
    -f testcases/* \
    -t 1 2 4 \
    --includeFilter insert update \
    --includeFilter core \
	  --host $GYMONGODB_HOST \
    --port $GYMONGODB_PORT \
    --threads $THREADS \
    --multidb $TABLES \
    --trialTime $TIME
}

# Main
main() {
  if [[ "$VERBOSITY" -gt "0" ]]
  then
    echobench
    echoperf
  fi

  if [[ "$SLEEP" -gt "0" ]]
  then
    echo sleeping $SLEEP....
    sleep $SLEEP
  fi

  if [[ "$GYMONGO_PYTHON" -gt "0" ]]
  then
    runperf
  fi

  if [[ "$GYMONGO_PYTHON" -gt "10" ]]
  then
    runperf-full
  fi

  if [[ "$GYMONGO_SYSBENCH" -gt "0" ]]
  then
    runbench
  fi

  if [[ "$#" -gt 0 ]]
  then
    exec "$@"
  else
    echo 'Thank for visiting the gymongonasium!'
  fi
}

main "$@"
